param(
    [string]$OutputDir = "scripts/sql"
)

function Escape-SqlValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    return $Value.Replace("'", "''")
}

$catalog = @(
    @{ Category = "CARDIO"; Items = @(
        @{ Zh = "快走"; En = "Brisk Walk" },
        @{ Zh = "慢跑"; En = "Jogging" },
        @{ Zh = "跑步机跑步"; En = "Treadmill Run" },
        @{ Zh = "骑行"; En = "Cycling" },
        @{ Zh = "动感单车"; En = "Spin Bike" },
        @{ Zh = "椭圆机"; En = "Elliptical" },
        @{ Zh = "游泳"; En = "Swimming" },
        @{ Zh = "跳绳"; En = "Jump Rope" },
        @{ Zh = "登阶机"; En = "Stair Climber" },
        @{ Zh = "划船机"; En = "Rowing Machine" }
    ); BaseMet = 3.5; Step = 0.5 },
    @{ Category = "STRENGTH"; Items = @(
        @{ Zh = "哑铃训练"; En = "Dumbbell Training" },
        @{ Zh = "杠铃训练"; En = "Barbell Training" },
        @{ Zh = "深蹲"; En = "Squat" },
        @{ Zh = "硬拉"; En = "Deadlift" },
        @{ Zh = "卧推"; En = "Bench Press" },
        @{ Zh = "壶铃训练"; En = "Kettlebell" },
        @{ Zh = "自重训练"; En = "Bodyweight Training" },
        @{ Zh = "俯卧撑"; En = "Push-up" },
        @{ Zh = "引体向上"; En = "Pull-up" },
        @{ Zh = "核心训练"; En = "Core Training" }
    ); BaseMet = 4.0; Step = 0.4 },
    @{ Category = "BALL"; Items = @(
        @{ Zh = "羽毛球"; En = "Badminton" },
        @{ Zh = "篮球"; En = "Basketball" },
        @{ Zh = "足球"; En = "Football" },
        @{ Zh = "网球"; En = "Tennis" },
        @{ Zh = "乒乓球"; En = "Table Tennis" },
        @{ Zh = "排球"; En = "Volleyball" },
        @{ Zh = "壁球"; En = "Squash" },
        @{ Zh = "飞盘"; En = "Frisbee" },
        @{ Zh = "高尔夫"; En = "Golf" },
        @{ Zh = "保龄球"; En = "Bowling" }
    ); BaseMet = 3.8; Step = 0.45 },
    @{ Category = "FLEXIBILITY"; Items = @(
        @{ Zh = "瑜伽"; En = "Yoga" },
        @{ Zh = "普拉提"; En = "Pilates" },
        @{ Zh = "拉伸"; En = "Stretching" },
        @{ Zh = "太极"; En = "Tai Chi" },
        @{ Zh = "灵活性训练"; En = "Mobility Flow" },
        @{ Zh = "泡沫轴放松"; En = "Foam Rolling" },
        @{ Zh = "流瑜伽"; En = "Yoga Flow" },
        @{ Zh = "核心拉伸"; En = "Core Stretch" }
    ); BaseMet = 2.5; Step = 0.3 },
    @{ Category = "DAILY"; Items = @(
        @{ Zh = "爬楼梯"; En = "Climbing Stairs" },
        @{ Zh = "家务"; En = "Housework" },
        @{ Zh = "拖地"; En = "Mopping" },
        @{ Zh = "搬运物品"; En = "Carry Supplies" },
        @{ Zh = "遛狗"; En = "Walk Dog" },
        @{ Zh = "通勤步行"; En = "Commute Walk" },
        @{ Zh = "户外散步"; En = "Outdoor Walk" },
        @{ Zh = "站立办公"; En = "Standing Desk" }
    ); BaseMet = 2.8; Step = 0.35 },
    @{ Category = "OTHER"; Items = @(
        @{ Zh = "高强度间歇训练"; En = "HIIT" },
        @{ Zh = "搏击操"; En = "Kickboxing" },
        @{ Zh = "跳舞"; En = "Dance" },
        @{ Zh = "尊巴"; En = "Zumba" },
        @{ Zh = "有氧操"; En = "Aerobics" },
        @{ Zh = "攀岩"; En = "Rock Climbing" },
        @{ Zh = "滑冰"; En = "Ice Skating" },
        @{ Zh = "滑雪"; En = "Skiing" }
    ); BaseMet = 4.5; Step = 0.5 }
)

$variants = @(
    @{ NameSuffix = ""; AliasSuffix = ""; Factor = 1.0; Source = "USDA" },
    @{ NameSuffix = "（中等）"; AliasSuffix = " (Medium)"; Factor = 1.12; Source = "MANUAL" }
)

$syncLines = @(
    "-- builtin exercise seed generated by scripts/generate-builtin-exercise-seed.ps1",
    "-- formula fields: met_value used with user weight and duration",
    ""
)

$idx = 1
foreach ($group in $catalog) {
    for ($i = 0; $i -lt $group.Items.Count; $i++) {
        $item = $group.Items[$i]
        $met = [math]::Round($group.BaseMet + (($i % 6) * $group.Step), 2)
        $sortOrder = if ($i -lt 6) { $i + 1 } else { 9999 }

        foreach ($variant in $variants) {
            $finalName = "$($item.Zh)$($variant.NameSuffix)"
            $finalMet = [math]::Round($met * $variant.Factor, 2)
            $sourceRef = "EX-$($idx.ToString('0000'))"
            $englishAlias = "$($item.En)$($variant.AliasSuffix)"
            $aliases = @(
                $finalName,
                $item.Zh,
                $item.En,
                $englishAlias,
                $group.Category,
                "exercise"
            ) | Where-Object { $_ } | Select-Object -Unique
            $aliasesText = Escape-SqlValue ($aliases -join ",")
            $nameSql = Escape-SqlValue $finalName

            $syncLines += "INSERT INTO exercise (name, met_value, category, source, source_ref, aliases, is_builtin, sort_order, created_at) VALUES ('$nameSql', $finalMet, '$($group.Category)', '$($variant.Source)', '$sourceRef', '$aliasesText', 1, $sortOrder, NOW()) ON DUPLICATE KEY UPDATE met_value = VALUES(met_value), category = VALUES(category), source = VALUES(source), source_ref = VALUES(source_ref), aliases = VALUES(aliases), is_builtin = VALUES(is_builtin), sort_order = VALUES(sort_order);"
            $idx++
        }
    }
}

$bootstrapLines = @(
    "-- builtin exercise bootstrap generated by scripts/generate-builtin-exercise-seed.ps1",
    "DELETE FROM exercise WHERE is_builtin = 1;",
    ""
) + $syncLines

[System.IO.Directory]::CreateDirectory($OutputDir) | Out-Null

$bootstrapPath = Join-Path $OutputDir "bootstrap-builtin-exercises-latest.sql"
$syncPath = Join-Path $OutputDir "sync-builtin-exercises-latest.sql"

[System.IO.File]::WriteAllLines($bootstrapPath, $bootstrapLines, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllLines($syncPath, $syncLines, [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $($idx - 1) builtin exercises to:"
Write-Output " - $bootstrapPath"
Write-Output " - $syncPath"
