CREATE DATABASE IF NOT EXISTS diet DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS 'xinqi_diet'@'localhost' IDENTIFIED BY 'XinqiDiet@2026!';
CREATE USER IF NOT EXISTS 'xinqi_diet'@'127.0.0.1' IDENTIFIED BY 'XinqiDiet@2026!';
GRANT ALL PRIVILEGES ON diet.* TO 'xinqi_diet'@'localhost';
GRANT ALL PRIVILEGES ON diet.* TO 'xinqi_diet'@'127.0.0.1';
FLUSH PRIVILEGES;
