spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diet?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xinqi_diet
    password: XinqiDiet@2026!
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.diet: debug

server:
  port: 8080