-- builtin food seed generated by scripts/generate-builtin-food-seed.js
-- source: offline curated real foods table
-- behavior: hide previous curated rows, then upsert current catalog by builtin name

UPDATE food SET source = 'LEGACY_BUILTIN' WHERE is_builtin = 1 AND source IN ('CURATED_CN', 'CURATED_GLOBAL');

UPDATE food
SET calories_per_100g = 116,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.6,
    carbs_per_100g = 25.9,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-001',
    aliases = '米饭,白米饭,白饭',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '米饭';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '米饭', 116, 'KCAL', 2.6, 25.9, 0.3, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-001', '米饭,白米饭,白饭', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '米饭');

UPDATE food
SET calories_per_100g = 111,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.6,
    carbs_per_100g = 23,
    fat_per_100g = 0.9,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-002',
    aliases = '糙米饭,糙米',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '糙米饭';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '糙米饭', 111, 'KCAL', 2.6, 23, 0.9, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-002', '糙米饭,糙米', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '糙米饭');

UPDATE food
SET calories_per_100g = 115,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.7,
    carbs_per_100g = 24.6,
    fat_per_100g = 1,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-003',
    aliases = '黑米饭,黑米',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '黑米饭';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '黑米饭', 115, 'KCAL', 2.7, 24.6, 1, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-003', '黑米饭,黑米', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '黑米饭');

UPDATE food
SET calories_per_100g = 120,
    calorie_unit = 'KCAL',
    protein_per_100g = 4.1,
    carbs_per_100g = 21.3,
    fat_per_100g = 1.9,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-STAPLE-004',
    aliases = '藜麦饭,藜麦',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '藜麦饭';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '藜麦饭', 120, 'KCAL', 4.1, 21.3, 1.9, 'G', '主食', 'CURATED_GLOBAL', 'CURATED-STAPLE-004', '藜麦饭,藜麦', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '藜麦饭');

UPDATE food
SET calories_per_100g = 46,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.4,
    carbs_per_100g = 9.3,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-005',
    aliases = '小米粥,小米稀饭',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '小米粥';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '小米粥', 46, 'KCAL', 1.4, 9.3, 0.3, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-005', '小米粥,小米稀饭', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '小米粥');

UPDATE food
SET calories_per_100g = 68,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.4,
    carbs_per_100g = 12,
    fat_per_100g = 1.4,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-006',
    aliases = '燕麦粥,燕麦片粥',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '燕麦粥';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '燕麦粥', 68, 'KCAL', 2.4, 12, 1.4, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-006', '燕麦粥,燕麦片粥', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '燕麦粥');

UPDATE food
SET calories_per_100g = 247,
    calorie_unit = 'KCAL',
    protein_per_100g = 13,
    carbs_per_100g = 41,
    fat_per_100g = 4.2,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-007',
    aliases = '全麦面包,全麦吐司',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '全麦面包';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '全麦面包', 247, 'KCAL', 13, 41, 4.2, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-007', '全麦面包,全麦吐司', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '全麦面包');

UPDATE food
SET calories_per_100g = 265,
    calorie_unit = 'KCAL',
    protein_per_100g = 8.3,
    carbs_per_100g = 49,
    fat_per_100g = 3.2,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-008',
    aliases = '白面包,吐司,切片面包',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '白面包';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '白面包', 265, 'KCAL', 8.3, 49, 3.2, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-008', '白面包,吐司,切片面包', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '白面包');

UPDATE food
SET calories_per_100g = 223,
    calorie_unit = 'KCAL',
    protein_per_100g = 7,
    carbs_per_100g = 47,
    fat_per_100g = 1.1,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-009',
    aliases = '馒头,白馒头',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '馒头';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '馒头', 223, 'KCAL', 7, 47, 1.1, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-009', '馒头,白馒头', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '馒头');

UPDATE food
SET calories_per_100g = 112,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.7,
    carbs_per_100g = 22.8,
    fat_per_100g = 1.2,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-010',
    aliases = '玉米,甜玉米,玉米粒',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '玉米';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '玉米', 112, 'KCAL', 2.7, 22.8, 1.2, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-010', '玉米,甜玉米,玉米粒', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '玉米');

UPDATE food
SET calories_per_100g = 86,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.6,
    carbs_per_100g = 20.1,
    fat_per_100g = 0.1,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-011',
    aliases = '红薯,地瓜,番薯',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '红薯';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '红薯', 86, 'KCAL', 1.6, 20.1, 0.1, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-011', '红薯,地瓜,番薯', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '红薯');

UPDATE food
SET calories_per_100g = 90,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.8,
    carbs_per_100g = 21,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-012',
    aliases = '紫薯,紫心红薯',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '紫薯';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '紫薯', 90, 'KCAL', 1.8, 21, 0.2, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-012', '紫薯,紫心红薯', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '紫薯');

UPDATE food
SET calories_per_100g = 77,
    calorie_unit = 'KCAL',
    protein_per_100g = 2,
    carbs_per_100g = 17.2,
    fat_per_100g = 0.1,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-013',
    aliases = '土豆,马铃薯',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '土豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '土豆', 77, 'KCAL', 2, 17.2, 0.1, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-013', '土豆,马铃薯', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '土豆');

UPDATE food
SET calories_per_100g = 157,
    calorie_unit = 'KCAL',
    protein_per_100g = 5.8,
    carbs_per_100g = 30.9,
    fat_per_100g = 0.9,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-STAPLE-014',
    aliases = '意面（熟）,意大利面',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '意面（熟）';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '意面（熟）', 157, 'KCAL', 5.8, 30.9, 0.9, 'G', '主食', 'CURATED_GLOBAL', 'CURATED-STAPLE-014', '意面（熟）,意大利面', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '意面（熟）');

UPDATE food
SET calories_per_100g = 99,
    calorie_unit = 'KCAL',
    protein_per_100g = 5.1,
    carbs_per_100g = 21.4,
    fat_per_100g = 0.1,
    quantity_unit = 'G',
    category = '主食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-STAPLE-015',
    aliases = '荞麦面（熟）,荞麦面',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '荞麦面（熟）';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '荞麦面（熟）', 99, 'KCAL', 5.1, 21.4, 0.1, 'G', '主食', 'CURATED_CN', 'CURATED-STAPLE-015', '荞麦面（熟）,荞麦面', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '荞麦面（熟）');

UPDATE food
SET calories_per_100g = 133,
    calorie_unit = 'KCAL',
    protein_per_100g = 24,
    carbs_per_100g = 0,
    fat_per_100g = 2.5,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-001',
    aliases = '鸡胸肉,鸡胸',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '鸡胸肉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鸡胸肉', 133, 'KCAL', 24, 0, 2.5, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-001', '鸡胸肉,鸡胸', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鸡胸肉');

UPDATE food
SET calories_per_100g = 181,
    calorie_unit = 'KCAL',
    protein_per_100g = 18.2,
    carbs_per_100g = 0,
    fat_per_100g = 12.2,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-002',
    aliases = '鸡腿肉,去皮鸡腿肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '鸡腿肉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鸡腿肉', 181, 'KCAL', 18.2, 0, 12.2, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-002', '鸡腿肉,去皮鸡腿肉', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鸡腿肉');

UPDATE food
SET calories_per_100g = 125,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.4,
    carbs_per_100g = 0,
    fat_per_100g = 4.2,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-003',
    aliases = '瘦牛肉,牛肉瘦',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '瘦牛肉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '瘦牛肉', 125, 'KCAL', 20.4, 0, 4.2, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-003', '瘦牛肉,牛肉瘦', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '瘦牛肉');

UPDATE food
SET calories_per_100g = 155,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.2,
    carbs_per_100g = 0,
    fat_per_100g = 7.4,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-004',
    aliases = '牛里脊,牛柳',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '牛里脊';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '牛里脊', 155, 'KCAL', 20.2, 0, 7.4, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-004', '牛里脊,牛柳', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '牛里脊');

UPDATE food
SET calories_per_100g = 143,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.5,
    carbs_per_100g = 0,
    fat_per_100g = 6.2,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-005',
    aliases = '猪里脊,里脊肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '猪里脊';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '猪里脊', 143, 'KCAL', 20.5, 0, 6.2, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-005', '猪里脊,里脊肉', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '猪里脊');

UPDATE food
SET calories_per_100g = 208,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.4,
    carbs_per_100g = 0,
    fat_per_100g = 13.4,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-PROTEIN-006',
    aliases = '三文鱼,鲑鱼',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '三文鱼';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '三文鱼', 208, 'KCAL', 20.4, 0, 13.4, 'G', '肉蛋奶', 'CURATED_GLOBAL', 'CURATED-PROTEIN-006', '三文鱼,鲑鱼', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '三文鱼');

UPDATE food
SET calories_per_100g = 82,
    calorie_unit = 'KCAL',
    protein_per_100g = 17.8,
    carbs_per_100g = 0,
    fat_per_100g = 0.7,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-PROTEIN-007',
    aliases = '鳕鱼,鳕鱼柳',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '鳕鱼';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鳕鱼', 82, 'KCAL', 17.8, 0, 0.7, 'G', '肉蛋奶', 'CURATED_GLOBAL', 'CURATED-PROTEIN-007', '鳕鱼,鳕鱼柳', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鳕鱼');

UPDATE food
SET calories_per_100g = 116,
    calorie_unit = 'KCAL',
    protein_per_100g = 25.5,
    carbs_per_100g = 0,
    fat_per_100g = 0.8,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-PROTEIN-008',
    aliases = '金枪鱼,吞拿鱼',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '金枪鱼';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '金枪鱼', 116, 'KCAL', 25.5, 0, 0.8, 'G', '肉蛋奶', 'CURATED_GLOBAL', 'CURATED-PROTEIN-008', '金枪鱼,吞拿鱼', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '金枪鱼');

UPDATE food
SET calories_per_100g = 99,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.4,
    carbs_per_100g = 0.7,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-009',
    aliases = '虾仁,虾肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '虾仁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '虾仁', 99, 'KCAL', 20.4, 0.7, 0.3, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-009', '虾仁,虾肉', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '虾仁');

UPDATE food
SET calories_per_100g = 144,
    calorie_unit = 'KCAL',
    protein_per_100g = 13.3,
    carbs_per_100g = 1.3,
    fat_per_100g = 9,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-010',
    aliases = '鸡蛋,全蛋',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '鸡蛋';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鸡蛋', 144, 'KCAL', 13.3, 1.3, 9, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-010', '鸡蛋,全蛋', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鸡蛋');

UPDATE food
SET calories_per_100g = 61,
    calorie_unit = 'KCAL',
    protein_per_100g = 3.2,
    carbs_per_100g = 4.8,
    fat_per_100g = 3.3,
    quantity_unit = 'ML',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-011',
    aliases = '纯牛奶,牛奶,全脂牛奶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '纯牛奶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '纯牛奶', 61, 'KCAL', 3.2, 4.8, 3.3, 'ML', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-011', '纯牛奶,牛奶,全脂牛奶', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '纯牛奶');

UPDATE food
SET calories_per_100g = 46,
    calorie_unit = 'KCAL',
    protein_per_100g = 3.4,
    carbs_per_100g = 5,
    fat_per_100g = 1.5,
    quantity_unit = 'ML',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-012',
    aliases = '低脂牛奶,低脂纯牛奶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '低脂牛奶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '低脂牛奶', 46, 'KCAL', 3.4, 5, 1.5, 'ML', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-012', '低脂牛奶,低脂纯牛奶', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '低脂牛奶');

UPDATE food
SET calories_per_100g = 63,
    calorie_unit = 'KCAL',
    protein_per_100g = 3.5,
    carbs_per_100g = 4,
    fat_per_100g = 2.9,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_CN',
    source_ref = 'CURATED-PROTEIN-013',
    aliases = '无糖酸奶,原味酸奶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '无糖酸奶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '无糖酸奶', 63, 'KCAL', 3.5, 4, 2.9, 'G', '肉蛋奶', 'CURATED_CN', 'CURATED-PROTEIN-013', '无糖酸奶,原味酸奶', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '无糖酸奶');

UPDATE food
SET calories_per_100g = 97,
    calorie_unit = 'KCAL',
    protein_per_100g = 9,
    carbs_per_100g = 3.9,
    fat_per_100g = 4.6,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-PROTEIN-014',
    aliases = '希腊酸奶（原味）,希腊酸奶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '希腊酸奶（原味）';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '希腊酸奶（原味）', 97, 'KCAL', 9, 3.9, 4.6, 'G', '肉蛋奶', 'CURATED_GLOBAL', 'CURATED-PROTEIN-014', '希腊酸奶（原味）,希腊酸奶', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '希腊酸奶（原味）');

UPDATE food
SET calories_per_100g = 328,
    calorie_unit = 'KCAL',
    protein_per_100g = 25,
    carbs_per_100g = 3.5,
    fat_per_100g = 25,
    quantity_unit = 'G',
    category = '肉蛋奶',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-PROTEIN-015',
    aliases = '奶酪,芝士',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '奶酪';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '奶酪', 328, 'KCAL', 25, 3.5, 25, 'G', '肉蛋奶', 'CURATED_GLOBAL', 'CURATED-PROTEIN-015', '奶酪,芝士', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '奶酪');

UPDATE food
SET calories_per_100g = 34,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.8,
    carbs_per_100g = 6.6,
    fat_per_100g = 0.4,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-001',
    aliases = '西兰花,西蓝花',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '西兰花';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '西兰花', 34, 'KCAL', 2.8, 6.6, 0.4, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-001', '西兰花,西蓝花', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '西兰花');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.3,
    carbs_per_100g = 2.2,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-002',
    aliases = '生菜,球生菜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '生菜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '生菜', 15, 'KCAL', 1.3, 2.2, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-002', '生菜,球生菜', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '生菜');

UPDATE food
SET calories_per_100g = 23,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.9,
    carbs_per_100g = 3.6,
    fat_per_100g = 0.4,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-003',
    aliases = '菠菜,菠菜叶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '菠菜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '菠菜', 23, 'KCAL', 2.9, 3.6, 0.4, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-003', '菠菜,菠菜叶', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '菠菜');

UPDATE food
SET calories_per_100g = 14,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.4,
    carbs_per_100g = 2.1,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-004',
    aliases = '油麦菜,莜麦菜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '油麦菜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '油麦菜', 14, 'KCAL', 1.4, 2.1, 0.3, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-004', '油麦菜,莜麦菜', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '油麦菜');

UPDATE food
SET calories_per_100g = 12,
    calorie_unit = 'KCAL',
    protein_per_100g = 1,
    carbs_per_100g = 2.2,
    fat_per_100g = 0.1,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-005',
    aliases = '白菜,大白菜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '白菜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '白菜', 12, 'KCAL', 1, 2.2, 0.1, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-005', '白菜,大白菜', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '白菜');

UPDATE food
SET calories_per_100g = 18,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.9,
    carbs_per_100g = 3.9,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-006',
    aliases = '番茄,西红柿',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '番茄';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '番茄', 18, 'KCAL', 0.9, 3.9, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-006', '番茄,西红柿', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '番茄');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.8,
    carbs_per_100g = 2.9,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-007',
    aliases = '黄瓜,青瓜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '黄瓜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '黄瓜', 15, 'KCAL', 0.8, 2.9, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-007', '黄瓜,青瓜', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '黄瓜');

UPDATE food
SET calories_per_100g = 41,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.9,
    carbs_per_100g = 9.6,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-008',
    aliases = '胡萝卜,红萝卜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '胡萝卜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '胡萝卜', 41, 'KCAL', 0.9, 9.6, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-008', '胡萝卜,红萝卜', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '胡萝卜');

UPDATE food
SET calories_per_100g = 16,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.7,
    carbs_per_100g = 3.4,
    fat_per_100g = 0.1,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-009',
    aliases = '白萝卜,萝卜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '白萝卜';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '白萝卜', 16, 'KCAL', 0.7, 3.4, 0.1, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-009', '白萝卜,萝卜', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '白萝卜');

UPDATE food
SET calories_per_100g = 31,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.4,
    carbs_per_100g = 7.4,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-010',
    aliases = '紫甘蓝,紫包菜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '紫甘蓝';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '紫甘蓝', 31, 'KCAL', 1.4, 7.4, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-010', '紫甘蓝,紫包菜', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '紫甘蓝');

UPDATE food
SET calories_per_100g = 31,
    calorie_unit = 'KCAL',
    protein_per_100g = 1,
    carbs_per_100g = 6,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-011',
    aliases = '彩椒,甜椒',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '彩椒';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '彩椒', 31, 'KCAL', 1, 6, 0.3, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-011', '彩椒,甜椒', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '彩椒');

UPDATE food
SET calories_per_100g = 34,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.2,
    carbs_per_100g = 6.8,
    fat_per_100g = 0.5,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-012',
    aliases = '香菇,鲜香菇',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '香菇';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '香菇', 34, 'KCAL', 2.2, 6.8, 0.5, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-012', '香菇,鲜香菇', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '香菇');

UPDATE food
SET calories_per_100g = 53,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.3,
    carbs_per_100g = 13.7,
    fat_per_100g = 0.2,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-013',
    aliases = '苹果,红苹果',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '苹果';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '苹果', 53, 'KCAL', 0.3, 13.7, 0.2, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-013', '苹果,红苹果', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '苹果');

UPDATE food
SET calories_per_100g = 93,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.1,
    carbs_per_100g = 22.8,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-014',
    aliases = '香蕉,香牙蕉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '香蕉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '香蕉', 93, 'KCAL', 1.1, 22.8, 0.3, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-014', '香蕉,香牙蕉', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '香蕉');

UPDATE food
SET calories_per_100g = 57,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.7,
    carbs_per_100g = 14.5,
    fat_per_100g = 0.3,
    quantity_unit = 'G',
    category = '蔬果',
    source = 'CURATED_CN',
    source_ref = 'CURATED-VEGETABLE_FRUIT-015',
    aliases = '蓝莓,蓝莓果',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '蓝莓';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '蓝莓', 57, 'KCAL', 0.7, 14.5, 0.3, 'G', '蔬果', 'CURATED_CN', 'CURATED-VEGETABLE_FRUIT-015', '蓝莓,蓝莓果', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '蓝莓');

UPDATE food
SET calories_per_100g = 446,
    calorie_unit = 'KCAL',
    protein_per_100g = 36.3,
    carbs_per_100g = 30.2,
    fat_per_100g = 19.6,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-001',
    aliases = '黄豆,大豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '黄豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '黄豆', 446, 'KCAL', 36.3, 30.2, 19.6, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-001', '黄豆,大豆', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '黄豆');

UPDATE food
SET calories_per_100g = 341,
    calorie_unit = 'KCAL',
    protein_per_100g = 21.6,
    carbs_per_100g = 33.4,
    fat_per_100g = 15,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-002',
    aliases = '黑豆,黑大豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '黑豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '黑豆', 341, 'KCAL', 21.6, 33.4, 15, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-002', '黑豆,黑大豆', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '黑豆');

UPDATE food
SET calories_per_100g = 324,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.2,
    carbs_per_100g = 57.2,
    fat_per_100g = 0.6,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-003',
    aliases = '红豆,赤小豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '红豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '红豆', 324, 'KCAL', 20.2, 57.2, 0.6, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-003', '红豆,赤小豆', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '红豆');

UPDATE food
SET calories_per_100g = 329,
    calorie_unit = 'KCAL',
    protein_per_100g = 23.8,
    carbs_per_100g = 62,
    fat_per_100g = 1.2,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-004',
    aliases = '绿豆,绿小豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '绿豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '绿豆', 329, 'KCAL', 23.8, 62, 1.2, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-004', '绿豆,绿小豆', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '绿豆');

UPDATE food
SET calories_per_100g = 131,
    calorie_unit = 'KCAL',
    protein_per_100g = 13,
    carbs_per_100g = 10.5,
    fat_per_100g = 5,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-005',
    aliases = '毛豆,青豆荚',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '毛豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '毛豆', 131, 'KCAL', 13, 10.5, 5, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-005', '毛豆,青豆荚', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '毛豆');

UPDATE food
SET calories_per_100g = 31,
    calorie_unit = 'KCAL',
    protein_per_100g = 3,
    carbs_per_100g = 1.6,
    fat_per_100g = 1.8,
    quantity_unit = 'ML',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-006',
    aliases = '豆浆,原味豆浆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '豆浆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '豆浆', 31, 'KCAL', 3, 1.6, 1.8, 'ML', '豆制品', 'CURATED_CN', 'CURATED-BEAN-006', '豆浆,原味豆浆', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '豆浆');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.8,
    carbs_per_100g = 0.9,
    fat_per_100g = 0.7,
    quantity_unit = 'ML',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-007',
    aliases = '无糖豆浆,无蔗糖豆浆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '无糖豆浆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '无糖豆浆', 15, 'KCAL', 1.8, 0.9, 0.7, 'ML', '豆制品', 'CURATED_CN', 'CURATED-BEAN-007', '无糖豆浆,无蔗糖豆浆', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '无糖豆浆');

UPDATE food
SET calories_per_100g = 98,
    calorie_unit = 'KCAL',
    protein_per_100g = 12.2,
    carbs_per_100g = 1.9,
    fat_per_100g = 4.8,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-008',
    aliases = '北豆腐,老豆腐',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '北豆腐';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '北豆腐', 98, 'KCAL', 12.2, 1.9, 4.8, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-008', '北豆腐,老豆腐', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '北豆腐');

UPDATE food
SET calories_per_100g = 57,
    calorie_unit = 'KCAL',
    protein_per_100g = 5,
    carbs_per_100g = 1.9,
    fat_per_100g = 2.7,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-009',
    aliases = '南豆腐,嫩豆腐',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '南豆腐';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '南豆腐', 57, 'KCAL', 5, 1.9, 2.7, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-009', '南豆腐,嫩豆腐', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '南豆腐');

UPDATE food
SET calories_per_100g = 140,
    calorie_unit = 'KCAL',
    protein_per_100g = 16.2,
    carbs_per_100g = 8.5,
    fat_per_100g = 6,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-010',
    aliases = '豆干,豆腐干',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '豆干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '豆干', 140, 'KCAL', 16.2, 8.5, 6, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-010', '豆干,豆腐干', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '豆干');

UPDATE food
SET calories_per_100g = 409,
    calorie_unit = 'KCAL',
    protein_per_100g = 44.6,
    carbs_per_100g = 18.5,
    fat_per_100g = 21.7,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-011',
    aliases = '豆腐皮,腐皮',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '豆腐皮';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '豆腐皮', 409, 'KCAL', 44.6, 18.5, 21.7, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-011', '豆腐皮,腐皮', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '豆腐皮');

UPDATE food
SET calories_per_100g = 461,
    calorie_unit = 'KCAL',
    protein_per_100g = 44.5,
    carbs_per_100g = 15.7,
    fat_per_100g = 24.2,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-012',
    aliases = '腐竹,干腐竹',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '腐竹';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '腐竹', 461, 'KCAL', 44.5, 15.7, 24.2, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-012', '腐竹,干腐竹', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '腐竹');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.6,
    carbs_per_100g = 1,
    fat_per_100g = 0.7,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-BEAN-013',
    aliases = '豆腐脑,豆花',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '豆腐脑';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '豆腐脑', 15, 'KCAL', 1.6, 1, 0.7, 'G', '豆制品', 'CURATED_CN', 'CURATED-BEAN-013', '豆腐脑,豆花', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '豆腐脑');

UPDATE food
SET calories_per_100g = 212,
    calorie_unit = 'KCAL',
    protein_per_100g = 18.4,
    carbs_per_100g = 12.7,
    fat_per_100g = 11,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-BEAN-014',
    aliases = '纳豆,发酵黄豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '纳豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '纳豆', 212, 'KCAL', 18.4, 12.7, 11, 'G', '豆制品', 'CURATED_GLOBAL', 'CURATED-BEAN-014', '纳豆,发酵黄豆', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '纳豆');

UPDATE food
SET calories_per_100g = 164,
    calorie_unit = 'KCAL',
    protein_per_100g = 8.9,
    carbs_per_100g = 27.4,
    fat_per_100g = 2.6,
    quantity_unit = 'G',
    category = '豆制品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-BEAN-015',
    aliases = '鹰嘴豆,鸡豆',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '鹰嘴豆';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鹰嘴豆', 164, 'KCAL', 8.9, 27.4, 2.6, 'G', '豆制品', 'CURATED_GLOBAL', 'CURATED-BEAN-015', '鹰嘴豆,鸡豆', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鹰嘴豆');

UPDATE food
SET calories_per_100g = 1,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.1,
    carbs_per_100g = 0,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-001',
    aliases = '美式咖啡,黑咖啡',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '美式咖啡';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '美式咖啡', 1, 'KCAL', 0.1, 0, 0, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-001', '美式咖啡,黑咖啡', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '美式咖啡');

UPDATE food
SET calories_per_100g = 43,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.3,
    carbs_per_100g = 4.8,
    fat_per_100g = 1.5,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-002',
    aliases = '拿铁,拿铁咖啡',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '拿铁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '拿铁', 43, 'KCAL', 2.3, 4.8, 1.5, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-002', '拿铁,拿铁咖啡', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '拿铁');

UPDATE food
SET calories_per_100g = 34,
    calorie_unit = 'KCAL',
    protein_per_100g = 2.5,
    carbs_per_100g = 4.5,
    fat_per_100g = 0.8,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-003',
    aliases = '低脂拿铁,脱脂拿铁',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '低脂拿铁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '低脂拿铁', 34, 'KCAL', 2.5, 4.5, 0.8, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-003', '低脂拿铁,脱脂拿铁', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '低脂拿铁');

UPDATE food
SET calories_per_100g = 1,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 0.2,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-004',
    aliases = '红茶,热红茶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '红茶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '红茶', 1, 'KCAL', 0, 0.2, 0, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-004', '红茶,热红茶', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '红茶');

UPDATE food
SET calories_per_100g = 0,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 0,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-005',
    aliases = '绿茶,清茶',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '绿茶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '绿茶', 0, 'KCAL', 0, 0, 0, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-005', '绿茶,清茶', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '绿茶');

UPDATE food
SET calories_per_100g = 0,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 0,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-006',
    aliases = '乌龙茶,乌龙',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '乌龙茶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '乌龙茶', 0, 'KCAL', 0, 0, 0, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-006', '乌龙茶,乌龙', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '乌龙茶');

UPDATE food
SET calories_per_100g = 3,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 0.8,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-007',
    aliases = '柠檬水,鲜柠檬水',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '柠檬水';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '柠檬水', 3, 'KCAL', 0, 0.8, 0, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-007', '柠檬水,鲜柠檬水', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '柠檬水');

UPDATE food
SET calories_per_100g = 19,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.7,
    carbs_per_100g = 4,
    fat_per_100g = 0.2,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-008',
    aliases = '椰子水,青椰水',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '椰子水';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '椰子水', 19, 'KCAL', 0.7, 4, 0.2, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-008', '椰子水,青椰水', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '椰子水');

UPDATE food
SET calories_per_100g = 17,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.8,
    carbs_per_100g = 4,
    fat_per_100g = 0.1,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-009',
    aliases = '番茄汁,西红柿汁',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '番茄汁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '番茄汁', 17, 'KCAL', 0.8, 4, 0.1, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-009', '番茄汁,西红柿汁', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '番茄汁');

UPDATE food
SET calories_per_100g = 45,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.7,
    carbs_per_100g = 10.4,
    fat_per_100g = 0.2,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-010',
    aliases = '橙汁,鲜榨橙汁',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '橙汁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '橙汁', 45, 'KCAL', 0.7, 10.4, 0.2, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-010', '橙汁,鲜榨橙汁', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '橙汁');

UPDATE food
SET calories_per_100g = 46,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.1,
    carbs_per_100g = 11.3,
    fat_per_100g = 0.1,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_CN',
    source_ref = 'CURATED-DRINK-011',
    aliases = '苹果汁,苹果果汁',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '苹果汁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '苹果汁', 46, 'KCAL', 0.1, 11.3, 0.1, 'ML', '饮品', 'CURATED_CN', 'CURATED-DRINK-011', '苹果汁,苹果果汁', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '苹果汁');

UPDATE food
SET calories_per_100g = 0,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 0,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-012',
    aliases = '无糖可乐,零度可乐',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '无糖可乐';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '无糖可乐', 0, 'KCAL', 0, 0, 0, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-012', '无糖可乐,零度可乐', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '无糖可乐');

UPDATE food
SET calories_per_100g = 42,
    calorie_unit = 'KCAL',
    protein_per_100g = 0,
    carbs_per_100g = 10.6,
    fat_per_100g = 0,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-013',
    aliases = '可乐,汽水可乐',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '可乐';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '可乐', 42, 'KCAL', 0, 10.6, 0, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-013', '可乐,汽水可乐', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '可乐');

UPDATE food
SET calories_per_100g = 46,
    calorie_unit = 'KCAL',
    protein_per_100g = 1,
    carbs_per_100g = 6.7,
    fat_per_100g = 1.5,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-014',
    aliases = '燕麦奶,燕麦饮',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '燕麦奶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '燕麦奶', 46, 'KCAL', 1, 6.7, 1.5, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-014', '燕麦奶,燕麦饮', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '燕麦奶');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.5,
    carbs_per_100g = 0.3,
    fat_per_100g = 1.2,
    quantity_unit = 'ML',
    category = '饮品',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-DRINK-015',
    aliases = '杏仁奶,杏仁饮',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '杏仁奶';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '杏仁奶', 15, 'KCAL', 0.5, 0.3, 1.2, 'ML', '饮品', 'CURATED_GLOBAL', 'CURATED-DRINK-015', '杏仁奶,杏仁饮', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '杏仁奶');

UPDATE food
SET calories_per_100g = 607,
    calorie_unit = 'KCAL',
    protein_per_100g = 20,
    carbs_per_100g = 21,
    fat_per_100g = 54,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-001',
    aliases = '混合坚果,坚果混合',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '混合坚果';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '混合坚果', 607, 'KCAL', 20, 21, 54, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-001', '混合坚果,坚果混合', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '混合坚果');

UPDATE food
SET calories_per_100g = 576,
    calorie_unit = 'KCAL',
    protein_per_100g = 21.2,
    carbs_per_100g = 21.7,
    fat_per_100g = 49.9,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-002',
    aliases = '杏仁,巴旦木',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '杏仁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '杏仁', 576, 'KCAL', 21.2, 21.7, 49.9, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-002', '杏仁,巴旦木', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '杏仁');

UPDATE food
SET calories_per_100g = 646,
    calorie_unit = 'KCAL',
    protein_per_100g = 15.2,
    carbs_per_100g = 13.7,
    fat_per_100g = 65.2,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-003',
    aliases = '核桃,胡桃',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '核桃';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '核桃', 646, 'KCAL', 15.2, 13.7, 65.2, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-003', '核桃,胡桃', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '核桃');

UPDATE food
SET calories_per_100g = 562,
    calorie_unit = 'KCAL',
    protein_per_100g = 20.6,
    carbs_per_100g = 28,
    fat_per_100g = 45.4,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-004',
    aliases = '开心果,开心果仁',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '开心果';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '开心果', 562, 'KCAL', 20.6, 28, 45.4, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-004', '开心果,开心果仁', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '开心果');

UPDATE food
SET calories_per_100g = 567,
    calorie_unit = 'KCAL',
    protein_per_100g = 25.8,
    carbs_per_100g = 16.1,
    fat_per_100g = 49.2,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-005',
    aliases = '花生,花生米',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '花生';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '花生', 567, 'KCAL', 25.8, 16.1, 49.2, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-005', '花生,花生米', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '花生');

UPDATE food
SET calories_per_100g = 299,
    calorie_unit = 'KCAL',
    protein_per_100g = 3.1,
    carbs_per_100g = 79.2,
    fat_per_100g = 0.5,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-006',
    aliases = '葡萄干,提子干',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '葡萄干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '葡萄干', 299, 'KCAL', 3.1, 79.2, 0.5, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-006', '葡萄干,提子干', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '葡萄干');

UPDATE food
SET calories_per_100g = 325,
    calorie_unit = 'KCAL',
    protein_per_100g = 0.1,
    carbs_per_100g = 82.4,
    fat_per_100g = 1.1,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-SNACK-007',
    aliases = '蔓越莓干,蔓越莓果干',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '蔓越莓干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '蔓越莓干', 325, 'KCAL', 0.1, 82.4, 1.1, 'G', '零食', 'CURATED_GLOBAL', 'CURATED-SNACK-007', '蔓越莓干,蔓越莓果干', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '蔓越莓干');

UPDATE food
SET calories_per_100g = 368,
    calorie_unit = 'KCAL',
    protein_per_100g = 27,
    carbs_per_100g = 35,
    fat_per_100g = 11,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-SNACK-008',
    aliases = '高蛋白棒,蛋白棒',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '高蛋白棒';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '高蛋白棒', 368, 'KCAL', 27, 35, 11, 'G', '零食', 'CURATED_GLOBAL', 'CURATED-SNACK-008', '高蛋白棒,蛋白棒', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '高蛋白棒');

UPDATE food
SET calories_per_100g = 450,
    calorie_unit = 'KCAL',
    protein_per_100g = 9,
    carbs_per_100g = 65,
    fat_per_100g = 16,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-009',
    aliases = '全麦饼干,全麦苏打饼',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '全麦饼干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '全麦饼干', 450, 'KCAL', 9, 65, 16, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-009', '全麦饼干,全麦苏打饼', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '全麦饼干');

UPDATE food
SET calories_per_100g = 408,
    calorie_unit = 'KCAL',
    protein_per_100g = 9,
    carbs_per_100g = 74,
    fat_per_100g = 8,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-010',
    aliases = '苏打饼干,咸味苏打饼',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '苏打饼干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '苏打饼干', 408, 'KCAL', 9, 74, 8, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-010', '苏打饼干,咸味苏打饼', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '苏打饼干');

UPDATE food
SET calories_per_100g = 338,
    calorie_unit = 'KCAL',
    protein_per_100g = 29.4,
    carbs_per_100g = 41.7,
    fat_per_100g = 3.7,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-011',
    aliases = '海苔,烤海苔',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '海苔';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '海苔', 338, 'KCAL', 29.4, 41.7, 3.7, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-011', '海苔,烤海苔', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '海苔');

UPDATE food
SET calories_per_100g = 387,
    calorie_unit = 'KCAL',
    protein_per_100g = 7.5,
    carbs_per_100g = 84,
    fat_per_100g = 1.6,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-SNACK-012',
    aliases = '玉米片,脆玉米片',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '玉米片';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '玉米片', 387, 'KCAL', 7.5, 84, 1.6, 'G', '零食', 'CURATED_GLOBAL', 'CURATED-SNACK-012', '玉米片,脆玉米片', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '玉米片');

UPDATE food
SET calories_per_100g = 387,
    calorie_unit = 'KCAL',
    protein_per_100g = 12.9,
    carbs_per_100g = 78,
    fat_per_100g = 4.5,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-SNACK-013',
    aliases = '爆米花,玉米爆花',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '爆米花';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '爆米花', 387, 'KCAL', 12.9, 78, 4.5, 'G', '零食', 'CURATED_GLOBAL', 'CURATED-SNACK-013', '爆米花,玉米爆花', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '爆米花');

UPDATE food
SET calories_per_100g = 598,
    calorie_unit = 'KCAL',
    protein_per_100g = 7.8,
    carbs_per_100g = 46.4,
    fat_per_100g = 42.6,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-SNACK-014',
    aliases = '黑巧克力,黑巧',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '黑巧克力';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '黑巧克力', 598, 'KCAL', 7.8, 46.4, 42.6, 'G', '零食', 'CURATED_GLOBAL', 'CURATED-SNACK-014', '黑巧克力,黑巧', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '黑巧克力');

UPDATE food
SET calories_per_100g = 330,
    calorie_unit = 'KCAL',
    protein_per_100g = 45,
    carbs_per_100g = 15,
    fat_per_100g = 12,
    quantity_unit = 'G',
    category = '零食',
    source = 'CURATED_CN',
    source_ref = 'CURATED-SNACK-015',
    aliases = '牛肉干,风干牛肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '牛肉干';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '牛肉干', 330, 'KCAL', 45, 15, 12, 'G', '零食', 'CURATED_CN', 'CURATED-SNACK-015', '牛肉干,风干牛肉', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '牛肉干');

UPDATE food
SET calories_per_100g = 109,
    calorie_unit = 'KCAL',
    protein_per_100g = 6.5,
    carbs_per_100g = 3.2,
    fat_per_100g = 7.8,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-001',
    aliases = '番茄炒蛋,西红柿炒鸡蛋',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 1
WHERE is_builtin = 1 AND name = '番茄炒蛋';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '番茄炒蛋', 109, 'KCAL', 6.5, 3.2, 7.8, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-001', '番茄炒蛋,西红柿炒鸡蛋', NULL, 1, 1, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '番茄炒蛋');

UPDATE food
SET calories_per_100g = 165,
    calorie_unit = 'KCAL',
    protein_per_100g = 14.2,
    carbs_per_100g = 8.6,
    fat_per_100g = 10.2,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-002',
    aliases = '宫保鸡丁,宫保鸡块',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 2
WHERE is_builtin = 1 AND name = '宫保鸡丁';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '宫保鸡丁', 165, 'KCAL', 14.2, 8.6, 10.2, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-002', '宫保鸡丁,宫保鸡块', NULL, 1, 2, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '宫保鸡丁');

UPDATE food
SET calories_per_100g = 48,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.6,
    carbs_per_100g = 5,
    fat_per_100g = 2.4,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-003',
    aliases = '清炒时蔬,炒青菜',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 3
WHERE is_builtin = 1 AND name = '清炒时蔬';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '清炒时蔬', 48, 'KCAL', 1.6, 5, 2.4, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-003', '清炒时蔬,炒青菜', NULL, 1, 3, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '清炒时蔬');

UPDATE food
SET calories_per_100g = 26,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.8,
    carbs_per_100g = 1.5,
    fat_per_100g = 1.4,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-004',
    aliases = '紫菜蛋花汤,蛋花汤',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 4
WHERE is_builtin = 1 AND name = '紫菜蛋花汤';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '紫菜蛋花汤', 26, 'KCAL', 1.8, 1.5, 1.4, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-004', '紫菜蛋花汤,蛋花汤', NULL, 1, 4, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '紫菜蛋花汤');

UPDATE food
SET calories_per_100g = 15,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.6,
    carbs_per_100g = 0.2,
    fat_per_100g = 0.8,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-005',
    aliases = '鸡汤,清鸡汤',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 5
WHERE is_builtin = 1 AND name = '鸡汤';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鸡汤', 15, 'KCAL', 1.6, 0.2, 0.8, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-005', '鸡汤,清鸡汤', NULL, 1, 5, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鸡汤');

UPDATE food
SET calories_per_100g = 32,
    calorie_unit = 'KCAL',
    protein_per_100g = 3.5,
    carbs_per_100g = 1.2,
    fat_per_100g = 1.6,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-006',
    aliases = '牛肉汤,清炖牛肉汤',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 6
WHERE is_builtin = 1 AND name = '牛肉汤';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '牛肉汤', 32, 'KCAL', 3.5, 1.2, 1.6, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-006', '牛肉汤,清炖牛肉汤', NULL, 1, 6, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '牛肉汤');

UPDATE food
SET calories_per_100g = 38,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.5,
    carbs_per_100g = 6,
    fat_per_100g = 1,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-007',
    aliases = '蔬菜沙拉,生菜沙拉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 7
WHERE is_builtin = 1 AND name = '蔬菜沙拉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '蔬菜沙拉', 38, 'KCAL', 1.5, 6, 1, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-007', '蔬菜沙拉,生菜沙拉', NULL, 1, 7, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '蔬菜沙拉');

UPDATE food
SET calories_per_100g = 145,
    calorie_unit = 'KCAL',
    protein_per_100g = 6,
    carbs_per_100g = 6.5,
    fat_per_100g = 11,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-OTHER-008',
    aliases = '凯撒沙拉,凯撒色拉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 8
WHERE is_builtin = 1 AND name = '凯撒沙拉';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '凯撒沙拉', 145, 'KCAL', 6, 6.5, 11, 'G', '其他', 'CURATED_GLOBAL', 'CURATED-OTHER-008', '凯撒沙拉,凯撒色拉', NULL, 1, 8, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '凯撒沙拉');

UPDATE food
SET calories_per_100g = 250,
    calorie_unit = 'KCAL',
    protein_per_100g = 10.5,
    carbs_per_100g = 28,
    fat_per_100g = 10.2,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-OTHER-009',
    aliases = '三明治,夹心三明治',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 9
WHERE is_builtin = 1 AND name = '三明治';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '三明治', 250, 'KCAL', 10.5, 28, 10.2, 'G', '其他', 'CURATED_GLOBAL', 'CURATED-OTHER-009', '三明治,夹心三明治', NULL, 1, 9, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '三明治');

UPDATE food
SET calories_per_100g = 150,
    calorie_unit = 'KCAL',
    protein_per_100g = 4.8,
    carbs_per_100g = 30,
    fat_per_100g = 1.5,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-OTHER-010',
    aliases = '寿司,日式寿司',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 10
WHERE is_builtin = 1 AND name = '寿司';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '寿司', 150, 'KCAL', 4.8, 30, 1.5, 'G', '其他', 'CURATED_GLOBAL', 'CURATED-OTHER-010', '寿司,日式寿司', NULL, 1, 10, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '寿司');

UPDATE food
SET calories_per_100g = 190,
    calorie_unit = 'KCAL',
    protein_per_100g = 4.5,
    carbs_per_100g = 37,
    fat_per_100g = 2.2,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-011',
    aliases = '饭团,三角饭团',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 11
WHERE is_builtin = 1 AND name = '饭团';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '饭团', 190, 'KCAL', 4.5, 37, 2.2, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-011', '饭团,三角饭团', NULL, 1, 11, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '饭团');

UPDATE food
SET calories_per_100g = 250,
    calorie_unit = 'KCAL',
    protein_per_100g = 12,
    carbs_per_100g = 24,
    fat_per_100g = 12,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-OTHER-012',
    aliases = '牛肉汉堡,汉堡包牛肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 12
WHERE is_builtin = 1 AND name = '牛肉汉堡';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '牛肉汉堡', 250, 'KCAL', 12, 24, 12, 'G', '其他', 'CURATED_GLOBAL', 'CURATED-OTHER-012', '牛肉汉堡,汉堡包牛肉', NULL, 1, 12, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '牛肉汉堡');

UPDATE food
SET calories_per_100g = 239,
    calorie_unit = 'KCAL',
    protein_per_100g = 13,
    carbs_per_100g = 25,
    fat_per_100g = 10,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_GLOBAL',
    source_ref = 'CURATED-OTHER-013',
    aliases = '鸡肉汉堡,汉堡包鸡肉',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 13
WHERE is_builtin = 1 AND name = '鸡肉汉堡';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '鸡肉汉堡', 239, 'KCAL', 13, 25, 10, 'G', '其他', 'CURATED_GLOBAL', 'CURATED-OTHER-013', '鸡肉汉堡,汉堡包鸡肉', NULL, 1, 13, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '鸡肉汉堡');

UPDATE food
SET calories_per_100g = 188,
    calorie_unit = 'KCAL',
    protein_per_100g = 4.8,
    carbs_per_100g = 31,
    fat_per_100g = 4.7,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-014',
    aliases = '炒饭,蛋炒饭',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 14
WHERE is_builtin = 1 AND name = '炒饭';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '炒饭', 188, 'KCAL', 4.8, 31, 4.7, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-014', '炒饭,蛋炒饭', NULL, 1, 14, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '炒饭');

UPDATE food
SET calories_per_100g = 35,
    calorie_unit = 'KCAL',
    protein_per_100g = 1.2,
    carbs_per_100g = 4,
    fat_per_100g = 1.6,
    quantity_unit = 'G',
    category = '其他',
    source = 'CURATED_CN',
    source_ref = 'CURATED-OTHER-015',
    aliases = '菌菇汤,蘑菇汤',
    image_url = NULL,
    is_builtin = 1,
    sort_order = 15
WHERE is_builtin = 1 AND name = '菌菇汤';

INSERT INTO food (name, calories_per_100g, calorie_unit, protein_per_100g, carbs_per_100g, fat_per_100g, quantity_unit, category, source, source_ref, aliases, image_url, is_builtin, sort_order, created_at)
SELECT '菌菇汤', 35, 'KCAL', 1.2, 4, 1.6, 'G', '其他', 'CURATED_CN', 'CURATED-OTHER-015', '菌菇汤,蘑菇汤', NULL, 1, 15, NOW()
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM food WHERE is_builtin = 1 AND name = '菌菇汤');
