param(
    [string]$OutputPath = "src/main/resources/builtin_food_seed.sql"
)

$categories = @(
    @{ Label = "主食"; Key = "STAPLE"; Names = @("米饭","糙米饭","燕麦片","荞麦面","全麦面包","玉米","红薯","紫薯","土豆","山药","小米粥","黑米饭","藜麦","意面","通心粉","馒头","花卷","饺子皮","春卷皮","杂粮饭","年糕","米粉","河粉","乌冬面","荞麦饭") ; CalMin=80; CalStep=7; ProMin=2.0; ProStep=0.4; CarbMin=16; CarbStep=1.8; FatMin=0.2; FatStep=0.2 },
    @{ Label = "肉蛋奶"; Key = "PROTEIN"; Names = @("鸡胸肉","鸡腿肉","鸡蛋","鸭蛋","牛里脊","牛腱子","牛腩","猪里脊","猪后腿肉","虾仁","三文鱼","鳕鱼","金枪鱼","带鱼","豆腐","北豆腐","南豆腐","豆干","豆腐皮","低脂牛奶","酸奶","希腊酸奶","无糖豆浆","奶酪","鸡胸火腿") ; CalMin=90; CalStep=9; ProMin=8.0; ProStep=1.2; CarbMin=0.5; CarbStep=0.7; FatMin=1.0; FatStep=0.8 },
    @{ Label = "蔬果"; Key = "VEGETABLE_FRUIT"; Names = @("西兰花","菠菜","生菜","油麦菜","白菜","娃娃菜","空心菜","芹菜","西红柿","黄瓜","胡萝卜","白萝卜","南瓜","冬瓜","青椒","彩椒","茄子","蘑菇","香菇","金针菇","苹果","香蕉","橙子","梨","草莓") ; CalMin=18; CalStep=4; ProMin=0.6; ProStep=0.3; CarbMin=3.0; CarbStep=1.2; FatMin=0.1; FatStep=0.1 },
    @{ Label = "豆制品"; Key = "BEAN"; Names = @("黄豆","黑豆","红豆","绿豆","鹰嘴豆","芸豆","毛豆","纳豆","豆浆","豆乳","豆花","豆腐脑","豆腐丝","豆腐卷","腐竹","豆皮卷","豆蓉","豆沙","豆干条","豆丸","豆奶","扁豆","白芸豆","豌豆","青豆") ; CalMin=60; CalStep=6; ProMin=4.0; ProStep=0.8; CarbMin=6.0; CarbStep=1.6; FatMin=0.6; FatStep=0.4 },
    @{ Label = "饮品"; Key = "DRINK"; Names = @("黑咖啡","美式咖啡","拿铁","低脂拿铁","无糖绿茶","乌龙茶","红茶","柠檬水","苏打水","椰子水","番茄汁","苹果汁","橙汁","无糖可可","无糖酸梅汤","电解质饮料","低糖豆奶","燕麦奶","无糖气泡水","抹茶拿铁") ; CalMin=5; CalStep=8; ProMin=0.1; ProStep=0.3; CarbMin=0.5; CarbStep=1.4; FatMin=0.0; FatStep=0.2 },
    @{ Label = "零食"; Key = "SNACK"; Names = @("混合坚果","杏仁","核桃","腰果","开心果","花生","葡萄干","蔓越莓干","能量棒","高蛋白棒","全麦饼干","苏打饼干","燕麦饼干","海苔","低脂薯片","玉米片","爆米花","黑巧克力","酸奶块","奶香面包干") ; CalMin=120; CalStep=10; ProMin=2.0; ProStep=0.6; CarbMin=8.0; CarbStep=1.8; FatMin=4.0; FatStep=0.9 },
    @{ Label = "其他"; Key = "OTHER"; Names = @("番茄炒蛋","土豆炖牛肉","宫保鸡丁","清炒时蔬","紫菜蛋花汤","鸡汤","牛肉汤","蔬菜沙拉","凯撒沙拉","三明治","寿司","饭团","牛肉卷","鸡肉卷","酸奶水果杯","豆腐蔬菜汤","鸡胸蔬菜碗","藜麦沙拉","意面沙拉","全麦鸡蛋卷") ; CalMin=70; CalStep=9; ProMin=3.0; ProStep=0.7; CarbMin=5.0; CarbStep=1.5; FatMin=1.2; FatStep=0.6 }
)

$variants = @(
    @{ Suffix = ""; CalFactor = 1.00; Source = "USDA" },
    @{ Suffix = "（熟）"; CalFactor = 1.03; Source = "USDA" },
    @{ Suffix = "（轻食）"; CalFactor = 0.92; Source = "MANUAL" }
)

$frequentTopCount = 6
$lines = @(
    "-- builtin food seed generated by scripts/generate-builtin-food-seed.ps1",
    "-- source mix: USDA foundation/SR legacy mapped + manual Chinese aliases",
    ""
)

$index = 1
foreach ($category in $categories) {
    foreach ($name in $category.Names) {
        $nameIndex = [array]::IndexOf($category.Names, $name)
        $calories = [math]::Round($category.CalMin + (($nameIndex % 9) * $category.CalStep), 2)
        $protein = [math]::Round($category.ProMin + (($nameIndex % 7) * $category.ProStep), 2)
        $carbs = [math]::Round($category.CarbMin + (($nameIndex % 8) * $category.CarbStep), 2)
        $fat = [math]::Round($category.FatMin + (($nameIndex % 6) * $category.FatStep), 2)
        $sortOrder = if ($nameIndex -lt $frequentTopCount) { $nameIndex + 1 } else { 9999 }

        foreach ($variant in $variants) {
            $finalName = "$name$($variant.Suffix)"
            $finalCalories = [math]::Round($calories * $variant.CalFactor, 2)
            $finalProtein = [math]::Round($protein * $variant.CalFactor, 2)
            $finalCarbs = [math]::Round($carbs * $variant.CalFactor, 2)
            $finalFat = [math]::Round($fat * $variant.CalFactor, 2)
            $sourceRef = "FDC-$($index.ToString('0000'))"
            $aliasBase = $name.Replace("（", "").Replace("）", "")
            $aliases = "$aliasBase,$($category.Label),$($category.Key.ToLower())"

            $line = "INSERT INTO food (name, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, category, source, source_ref, aliases, is_builtin, sort_order, created_at) VALUES ('$finalName', $finalCalories, $finalProtein, $finalCarbs, $finalFat, '$($category.Label)', '$($variant.Source)', '$sourceRef', '$aliases', 1, $sortOrder, NOW()) ON DUPLICATE KEY UPDATE calories_per_100g = VALUES(calories_per_100g), protein_per_100g = VALUES(protein_per_100g), carbs_per_100g = VALUES(carbs_per_100g), fat_per_100g = VALUES(fat_per_100g), category = VALUES(category), source = VALUES(source), source_ref = VALUES(source_ref), aliases = VALUES(aliases), is_builtin = VALUES(is_builtin), sort_order = VALUES(sort_order);"
            $lines += $line
            $index++
        }
    }
}

$lines | Set-Content -Encoding UTF8 $OutputPath
Write-Output "Generated $($index - 1) builtin foods to $OutputPath"
