param(
    [string]$OutputDir = "scripts/sql"
)

$catalog = @(
    @{ Category = "CARDIO"; Names = @("Brisk Walk", "Jogging", "Treadmill Run", "Cycling", "Spin Bike", "Elliptical", "Swimming", "Jump Rope", "Stair Climber", "Rowing Machine"); BaseMet = 3.5; Step = 0.5 },
    @{ Category = "STRENGTH"; Names = @("Dumbbell Training", "Barbell Training", "Squat", "Deadlift", "Bench Press", "Kettlebell", "Bodyweight Training", "Push-up", "Pull-up", "Core Training"); BaseMet = 4.0; Step = 0.4 },
    @{ Category = "BALL"; Names = @("Badminton", "Basketball", "Football", "Tennis", "Table Tennis", "Volleyball", "Squash", "Frisbee", "Golf", "Bowling"); BaseMet = 3.8; Step = 0.45 },
    @{ Category = "FLEXIBILITY"; Names = @("Yoga", "Pilates", "Stretching", "Tai Chi", "Mobility Flow", "Foam Rolling", "Yoga Flow", "Core Stretch"); BaseMet = 2.5; Step = 0.3 },
    @{ Category = "DAILY"; Names = @("Climbing Stairs", "Housework", "Mopping", "Carry Supplies", "Walk Dog", "Commute Walk", "Outdoor Walk", "Standing Desk"); BaseMet = 2.8; Step = 0.35 },
    @{ Category = "OTHER"; Names = @("HIIT", "Kickboxing", "Dance", "Zumba", "Aerobics", "Rock Climbing", "Ice Skating", "Skiing"); BaseMet = 4.5; Step = 0.5 }
)

$variants = @(
    @{ Suffix = ""; Factor = 1.0; Source = "USDA" },
    @{ Suffix = " (Medium)"; Factor = 1.12; Source = "MANUAL" }
)

$syncLines = @(
    "-- builtin exercise seed generated by scripts/generate-builtin-exercise-seed.ps1",
    "-- formula fields: met_value used with user weight and duration",
    ""
)

$idx = 1
foreach ($group in $catalog) {
    for ($i = 0; $i -lt $group.Names.Count; $i++) {
        $name = $group.Names[$i]
        $met = [math]::Round($group.BaseMet + (($i % 6) * $group.Step), 2)
        $sortOrder = if ($i -lt 6) { $i + 1 } else { 9999 }

        foreach ($variant in $variants) {
            $finalName = "$name$($variant.Suffix)"
            $finalMet = [math]::Round($met * $variant.Factor, 2)
            $sourceRef = "EX-$($idx.ToString('0000'))"
            $aliases = "$name,$($group.Category),exercise"

            $syncLines += "INSERT INTO exercise (name, met_value, category, source, source_ref, aliases, is_builtin, sort_order, created_at) VALUES ('$finalName', $finalMet, '$($group.Category)', '$($variant.Source)', '$sourceRef', '$aliases', 1, $sortOrder, NOW()) ON DUPLICATE KEY UPDATE met_value = VALUES(met_value), category = VALUES(category), source = VALUES(source), source_ref = VALUES(source_ref), aliases = VALUES(aliases), is_builtin = VALUES(is_builtin), sort_order = VALUES(sort_order);"
            $idx++
        }
    }
}

$bootstrapLines = @(
    "-- builtin exercise bootstrap generated by scripts/generate-builtin-exercise-seed.ps1",
    "DELETE FROM exercise WHERE is_builtin = 1;",
    ""
) + $syncLines

[System.IO.Directory]::CreateDirectory($OutputDir) | Out-Null

$bootstrapPath = Join-Path $OutputDir "bootstrap-builtin-exercises-latest.sql"
$syncPath = Join-Path $OutputDir "sync-builtin-exercises-latest.sql"

[System.IO.File]::WriteAllLines($bootstrapPath, $bootstrapLines, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllLines($syncPath, $syncLines, [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $($idx - 1) builtin exercises to:"
Write-Output " - $bootstrapPath"
Write-Output " - $syncPath"
